const db = require('../../database/database');
const userController = {};

userController.createUser = async (req, res, next) => {
  try {
    const { username, password, zipcode } = req.body;
    db.query(
      `INSERT INTO Users (user_name, user_password_hash, zipcode, listed_items)
    VALUES ('${username}', '${password}', '${zipcode}', null)`,
      (err, result, fields) => {
        if (err) {
          console.log('Error in the query', err);
        } else {
          console.log(result);
        }
      }
    );
    return next();
  } catch (error) {
    return next({
      log: 'Error creating new user',
      status: 400,
      message: { err: 'An error occurred in new user creation' },
    });
  }
};

userController.getUser = async (req, res, next) => {
  try {
    const { username, password } = req.body;

    await db.query(
      // SELECT column_name FROM table_name WHERE condition
      `SELECT user_password_hash FROM Users WHERE user_name = '${username}'`,
      (err, result, fields) => {
        if (err) {
          console.log('Error in the query', err);
        } else {
          console.log('query result is ', result);
          let foundPassword = result[0].user_password_hash;
          foundPassword === password
            ? (res.locals.authorizedUser = true)
            : (res.locals.authorizedUser = false);
        //   if (foundPassword === password) {
        //     console.log('pw is good');
        //     // console.log('returnedQ outside promise', returnedQuery)
        //     return next();
        //   } else {
        //     console.log('pw should be wrong');
        //     // console.log('returnedQ outside promise', returnedQuery)
        //     return next();
        // }
        return next();
        }
      }
    );
  } catch (error) {
    return next({
      log: 'Error logging in user',
      status: 400,
      message: { err: 'An error occurred in user login' },
    });
  }
};

module.exports = userController;
// export default userController
